# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SampleProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for Tbiby.Tn
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'Alamofire','~> 4.9.1'
  pod 'IQKeyboardManagerSwift'
  pod 'TextFieldEffects'
  pod 'lottie-ios'
  pod 'CalendarKit'
  pod 'FSCalendar'
  pod 'SwiftDate'
  pod 'Floaty'
  # Pods for SampleProject

end
